[preface]
== Glossário Rápido

Este glossário rápido contém muitos dos termos usados em relação ao bitcoin. Esses termos são usados em todo o livro, portanto, marque-os para uma referência rápida.

endereço::
    Um endereço bitcoin parece +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. Consiste em uma sequência de letras e números. Na verdade, é uma versão codificada de base58check de um hash de chave pública de 160 bits. Assim como você pede a outros que enviem um e-mail para o seu endereço de e-mail, você pediria que outros enviassem bitcoin para um de seus endereços de bitcoin.

bip::
    Bitcoin Improvement Proposals (Propostas de Melhoria do Bitcoin). Um conjunto de propostas que membros da comunidade bitcoin enviaram para melhorar o bitcoin. Por exemplo, o BIP-21 é uma proposta para melhorar o esquema de identificador uniforme de recursos bitcoin (URI).

bitcoin::
    O nome da unidade monetária (a moeda), a rede e o software.

bloco::
    Um agrupamento de transações, marcadas com um carimbo de data/hora e uma impressão digital do bloco anterior. O cabeçalho do bloco é hash para produzir uma prova de trabalho, validando assim as transações. Os blocos válidos são adicionados ao blockchain principal por consenso da rede.

blockchain::
	Uma lista de blocos validados, cada um vinculado ao seu antecessor até o bloco de origem.

Problema dos Generais Bizantinos::
    Um sistema de computador confiável deve ser capaz de lidar com a falha de um ou mais de seus componentes. Um componente com falha pode exibir um tipo de comportamento que costuma ser esquecido - ou seja, enviar informações conflitantes para diferentes partes do sistema. O problema de lidar com esse tipo de falha é expresso abstratamente como o Problema dos Generais Bizantinos.

coinbase::
	Um campo especial usado como entrada única para transações coinbase. O coinbase permite reivindicar a recompensa do bloco e fornece até 100 bytes para dados arbitrários.
	Não deve ser confundido com a transação Coinbase.

transação coinbase::
	A primeira transação em um bloco. Sempre criado por um mineiro, inclui uma única base de moedas.
	Não deve ser confundido com Coinbase.

armazenamento frio::
	Refere-se a manter uma reserva de bitcoin offline. O armazenamento frio é obtido quando as chaves privadas Bitcoin são criadas e armazenadas em um ambiente offline seguro. O armazenamento refrigerado é importante para qualquer pessoa com reservas de bitcoin. Os computadores online são vulneráveis a hackers e não devem ser usados para armazenar uma quantidade significativa de bitcoin.

confirmações::
	Uma vez que uma transação é incluída em um bloco, ela tem uma confirmação. Assim que _outro_ bloco é extraído no mesmo blockchain, a transação tem duas confirmações e assim por diante. Seis ou mais confirmações são consideradas prova suficiente de que uma transação não pode ser revertida.

consenso::
    Quando vários nós, geralmente a maioria dos nós na rede, têm os mesmos blocos em sua melhor cadeia de blocos validada localmente.
    Não deve ser confundido com regras de consenso.

regras de consenso::
    As regras de validação de bloco que os nós completos seguem para permanecer em consenso com outros nós.
    Não deve ser confundido com consenso.

dificuldade::
	Uma configuração em toda a rede que controla quanta computação é necessária para produzir uma prova de trabalho.

alvejamento de dificuldade::
	Um recálculo da dificuldade em toda a rede que ocorre uma vez a cada 2.016 blocos e considera o poder de hashing dos 2.016 blocos anteriores.

alvo de dificuldade::
    Uma dificuldade em que todo o cálculo na rede encontrará blocos aproximadamente a cada 10 minutos.

gasto duplo::
    Gasto duplo é o resultado de gastar algum dinheiro com sucesso mais de uma vez. O Bitcoin protege contra gastos duplos verificando cada transação adicionada à cadeia de blocos para garantir que as entradas para a transação ainda não tenham sido gastas anteriormente.

ECDSA::
    Elliptic Curve Digital Signature Algorithm ou ECDSA é um algoritmo criptográfico usado pelo Bitcoin para garantir que os fundos só possam ser gastos por seus legítimos proprietários.

nonce extra::
    À medida que a dificuldade aumentava, os mineiros frequentemente percorriam todos os 4 bilhões de valores do nonce sem encontrar um bloco. Como o script coinbase pode armazenar entre 2 e 100 bytes de dados, os mineiros começaram a usar esse espaço como espaço extra de nonce, permitindo-lhes explorar uma gama muito maior de valores de cabeçalho de bloco para encontrar blocos válidos.

honorários::
	O remetente de uma transação geralmente inclui uma taxa para a rede pelo processamento da transação solicitada. A maioria das transações exige uma taxa mínima de 0,5 mBTC.

fork (bifurcação)::
    Bifurcação, também conhecido como bifurcação acidental, ocorre quando dois ou mais blocos têm a mesma altura, bifurcando a corrente do bloco. Normalmente ocorre quando dois ou mais mineiros encontram blocos quase ao mesmo tempo. Também pode acontecer como parte de um ataque.

bloco de gêneses::
	O primeiro bloco no blockchain, usado para inicializar a criptomoeda.

hard fork::
    Hard fork, também conhecido como Hard-Forking Change, é uma divergência permanente no blockchain, comumente ocorre quando nós não atualizados não podem validar blocos criados por nós atualizados que seguem regras de consenso mais recentes.
    Não deve ser confundido com fork, soft fork, software fork ou Git fork.

carteira de hardware::
    Uma carteira de hardware é um tipo especial de carteira bitcoin que armazena as chaves privadas do usuário em um dispositivo de hardware seguro.

hash::
    Uma impressão digital de alguma entrada binária.

hashlocks::
    Um hashlock é um tipo de estorvo que restringe o gasto de uma saída até que um dado específico seja divulgado publicamente. Hashlocks têm a propriedade útil de que, uma vez que qualquer hashlock seja aberto publicamente, qualquer outro hashlock protegido usando a mesma chave também pode ser aberto. Isso torna possível criar várias saídas que são todas sobrecarregadas pelo mesmo hashlock e que se tornam gastas ao mesmo tempo.

protocolo HD::
    O protocolo Hierárquica Determinística (HD) de transferência e criação de chave (BIP-32), que permite criar chaves filho a partir de chaves pai em uma hierarquia.

carteira HD::
    Carteiras usando a criação de chave Hierárquica Determinística (Protocolo HD) e protocolo de transferência (BIP-32).

fundamento carteira HD::
    Fundamento da carteira HD ou fundamento raiz é um valor potencialmente curto usado como fundamento para gerar a chave privada mestra e o código de cadeia mestre para uma carteira HD.

HTLC::
    Um contrato Hashed TimeLock ou HTLC é uma classe de pagamentos que usa hashlocks e timelocks para exigir que o destinatário de um pagamento reconheça o recebimento do pagamento antes de um prazo, gerando prova criptográfica de pagamento ou perca a capacidade de reivindicar o pagamento, devolvendo-o para o pagador.

KYC::
    Know your customer (KYC), Conheça seu cliente, é o processo de uma empresa, identificando e verificando a identidade de seus clientes. O termo também é usado para se referir ao regulamento bancário que rege essas atividades.

LevelDB::
    LevelDB é um armazenamento de valores-chave em disco de código aberto. LevelDB é uma biblioteca leve e de propósito único para persistência com ligações para muitas plataformas.

Lightning Networks (Rede Relâmpago)::
    Lightning Network é uma implementação de Hashed Timelock Contracts (HTLCs) com canais de pagamento bidirecionais que permitem que os pagamentos sejam roteados com segurança em vários canais de pagamento ponto-a-ponto. Isso permite a formação de uma rede onde qualquer ponto da rede pode pagar a qualquer outro ponto, mesmo que eles não tenham um canal aberto diretamente entre eles.

Locktime::
    Locktime, ou mais tecnicamente nLockTime, é a parte de uma transação que indica a hora ou o bloco mais antigo quando essa transação pode ser adicionada à cadeia de blocos.

mempool::
    O bitcoin Mempool (pool de memória) é uma coleção de todos os dados de transação em um bloco que foram verificados por nós bitcoin, mas ainda não foram confirmados.

merkle root::
    O nó raiz de uma árvore merkle, um descendente de todos os pares de hash na árvore. Os cabeçalhos de bloco devem incluir uma raiz merkle válida descendente de todas as transações naquele bloco.

árvore merkle::
    Uma árvore construída por hash de dados emparelhados (as folhas), em seguida, emparelhando e hash dos resultados até que um único hash permaneça, a raiz do merkle. No Bitcoin, as folhas quase sempre são transações de um único bloco.

mineiro::
    Um nó de rede que encontra uma prova-de-trabalho válida para novos blocos, por hash repetido.

multisignature::
    Multisignature (multisig) refere-se à exigência de um número mínimo (M) de chaves (N) para autorizar uma transação M-of-N.

rede::
    Uma rede ponto-a-ponto que propaga transações e blocos para cada nó bitcoin na rede.

nonce::
    O "nonce" em um bloco de bitcoin é um campo de 32 bits (4 bytes) cujo valor é definido de forma que o hash do bloco contenha uma sequência de zeros à esquerda. Os demais campos não podem ser alterados, pois possuem um significado definido.

transações fora da cadeia::
    Uma transação fora da cadeia é o movimento de valor fora da cadeia de blocos. Enquanto uma transação em cadeia&#x2014;geralmente referido como simplesmente __uma transação__&#x2014;modifica o blockchain e depende do blockchain para determinar sua validade, uma transação fora da cadeia depende de outros métodos para registrar e validar a transação.

opcode::
    Códigos de operação da linguagem Bitcoin Script que enviam dados ou executam funções em um script pubkey ou script de assinatura.

Protocolo de Ativos Abertos::
    O Protocolo de Ativos Abertos é um protocolo simples e poderoso construído em cima do blockchain bitcoin. Ele permite a emissão e transferência de ativos criados pelo usuário.

OP_RETURN::
    Um opcode usado em uma das saídas em uma transação OP_RETURN. Não deve ser confundido com a transação OP_RETURN.

transação OP_RETURN::
    Um tipo de transação que adiciona dados arbitrários a um script pubkey comprovadamente impossível de gastar que os nós completos não precisam armazenar em seu banco de dados UTXO. Não deve ser confundido com opcode OP_RETURN.

bloco órfão::
    Blocos cujo bloco pai não foi processado pelo nó local, portanto, ainda não podem ser totalmente validados. Não deve ser confundido com bloco obsoleto.

transações órfãs::
    Transações que não podem entrar no pool devido a uma ou mais transações de entrada ausentes.

output (saída)::
    Saída, saída de transação ou TxOut é uma saída em uma transação que contém dois campos: um campo de valor para transferir zero ou mais satoshis e um script pubkey para indicar quais condições devem ser cumpridas para que esses satoshis sejam gastos posteriormente.

P2PKH::
    As transações que pagam um endereço bitcoin contêm scripts P2PKH ou Pay To PubKey Hash. Uma saída bloqueada por um script P2PKH pode ser desbloqueada (gasta) apresentando uma chave pública e uma assinatura digital criada pela chave privada correspondente.

P2SH::
    P2SH ou Pay-to-Script-Hash é um novo tipo poderoso de transação que simplifica muito o uso de scripts de transação complexos. Com P2SH, o script complexo que detalha as condições para gastar a saída (script de resgate) não é apresentado no script de bloqueio. Em vez disso, apenas um hash dele está no script de bloqueio.

endereço P2SH::
    Os endereços P2SH são codificações Base58Check do hash de 20 bytes de um script. Eles usam o prefixo de versão "5", que resulta em endereços codificados por Base58Check que começam com "3". Os endereços P2SH escondem toda a complexidade, para que a pessoa que faz o pagamento não veja o script.

P2WPKH::
    A assinatura de um P2WPKH (Pay-to-Witness-Public-Key-Hash) contém as mesmas informações de um gasto P2PKH, mas está localizado no campo witness em vez do campo scriptSig. O scriptPubKey também é modificado.

P2WSH::
    A diferença entre P2SH e P2WSH (Pay-to-Witness-Script-Hash) é sobre a alteração do local da prova criptográfica do campo scriptSig para o campo witness e o scriptPubKey que também é modificado.

paper wallet::
    No sentido mais específico, uma paper wallet é um documento que contém todos os dados necessários para gerar qualquer número de chaves privadas Bitcoin, formando uma carteira de chaves. No entanto, as pessoas costumam usar o termo para se referir a qualquer maneira de armazenar bitcoin offline como um documento físico. Esta segunda definição também inclui paper keys e códigos resgatáveis.

frase secreta::
    Uma frase secreta é uma string opcional criada pelo usuário que serve como um fator de segurança adicional protegendo o fundamento, mesmo quando o fundamento é comprometida por um ladrão. Também pode ser usado como uma forma de negação plausível, em que uma frase-senha escolhida leva a uma carteira com uma pequena quantia de fundos usada para desviar um invasor da carteira “real” que contém a maioria dos fundos.

canais de pagamento::
    Um canal de micropagamento ou canal de pagamento é uma classe de técnicas projetada para permitir que os usuários façam várias transações de bitcoin sem comprometer todas as transações com o blockchain de bitcoin. Em um canal de pagamento típico, apenas duas transações são adicionadas à cadeia de blocos, mas um número ilimitado ou quase ilimitado de pagamentos pode ser feito entre os participantes.

pool de mineração::
    Um pool de mineração é uma abordagem de mineração em que vários clientes de geração contribuem para a geração de um bloco e, em seguida, dividem a recompensa do bloco de acordo com o poder de processamento contribuído.

Proof-of-Stake (Prova-de-Aposta)::
    Proof-of-Stake (PoS) é um método pelo qual uma rede de blockchain de criptomoeda visa alcançar um consenso distribuído. O Proof-of-Stake pede aos usuários que comprovem a propriedade de uma determinada quantidade de moeda (sua "aposta" na moeda).

Proof-of-Work (Prova-de-Trabalho)::
    Um dado que requer computação significativa para ser encontrado. No bitcoin, os mineiros devem encontrar uma solução numérica para o algoritmo SHA256 que atenda a um alvo de toda a rede, o alvo de dificuldade.

reward (recompensa)::
    Um valor incluído em cada novo bloco como uma recompensa pela rede ao minerador que encontrou a solução de Prova-de-Trabalho. Atualmente é 6,25 BTC por bloco.

RIPEMD-160::
    RIPEMD-160 é uma função hash criptográfica de 160 bits. O RIPEMD-160 é uma versão reforçada do RIPEMD com um resultado hash de 160 bits e deve ser seguro nos próximos dez anos ou mais.

satoshi::
    Um satoshi é a menor denominação de bitcoin que pode ser registrada no blockchain. É o equivalente a 0,00000001 bitcoin e tem o nome do criador do Bitcoin, Satoshi Nakamoto. ((("satoshi")))

Satoshi Nakamoto::
    Satoshi Nakamoto é o nome usado pela pessoa ou pessoas que projetaram o Bitcoin e criaram sua implementação de referência original, Bitcoin Core. Como parte da implementação, eles também criaram o primeiro banco de dados de blockchain. No processo, eles foram os primeiros a resolver o problema do duplo gasto com moeda digital. Sua verdadeira identidade permanece desconhecida.

Script::
    Bitcoin usa um sistema de script para transações. Da mesma forma, o Script é simples, baseado em pilha e processado da esquerda para a direita. É propositalmente não Turing completo, sem loops.

ScriptPubKey (também conhecido como pubkey script)::
    ScriptPubKey ou script pubkey, é um script incluído nas saídas que define as condições que devem ser cumpridas para que esses satoshis sejam gastos. Os dados para o cumprimento das condições podem ser fornecidos em um script de assinatura.

ScriptSig (também conhecido como signature script)::
    ScriptSig ou script de assinatura, são os dados gerados por um gastador que quase sempre são usados como variáveis para satisfazer um pubkey script.

secret key (também conhecido como private key)::
    O número secreto que desbloqueia o bitcoin enviado para o endereço correspondente. Uma chave pass:[<span class="keep-together">secreta</span>] se parece com o seguinte:
+
----
5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh
----

Segregated Witness (Testemunha Segregada)::
    A Testemunha Segregada é uma atualização do protocolo Bitcoin no qual os dados de assinatura ("witness") são separados dos dados do remetente/receptor para otimizar ainda mais a estrutura das transações. O Segregated Witness foi implementado como um soft fork; uma mudança que tecnicamente torna as regras de protocolo do Bitcoin mais restritivas.

SHA::
    O Secure Hash Algorithm ou SHA é uma família de funções criptográficas de hash publicadas pelo National Institute of Standards and Technology (NIST).

Simplified Payment Verification (SPV) (Verificação de Pagamento Simplificada)::
    SPV ou verificação de pagamento simplificada é um método para verificar se determinadas transações foram incluídas em um bloco, sem baixar o bloco inteiro. Este método de verificação é frequentemente usado por clientes Bitcoin leves.

soft fork::
    Soft fork ou Soft-Forking Change é uma bifurcação temporária no blockchain que normalmente ocorre quando os mineiros que usam nós não atualizados não seguem uma nova regra de consenso sobre a qual seus nós não conhecem.
    Não deve ser confundido com fork, hard fork, software fork ou Git fork.

stale block (bloco velho)::
    Bloco que foi extraído com sucesso, mas que não está incluído na melhor corrente de bloco atual, provavelmente porque algum outro bloco na mesma altura teve sua corrente estendida primeiro. Não deve ser confundido com o bloco órfão.

timelocks::
    Um timelock é um tipo de estorvo que restringe o gasto de algum bitcoin até um determinado momento futuro ou altura de bloco. Os timelocks aparecem com destaque em muitos contratos Bitcoin, incluindo canais de pagamento e contratos de timelock com hash.

transação::
    Em termos simples, uma transferência de bitcoin de um endereço para outro. Mais precisamente, uma transação é uma estrutura de dados assinada que expressa uma transferência de valor. As transações são transmitidas pela rede bitcoin, coletadas pelos mineiros e incluídas em blocos, tornados permanentes no blockchain.

pool de transações::
    Uma coleção não ordenada de transações que não estão em blocos na cadeia principal, mas para as quais temos transações de entrada.

Turing completeness (completude de Turing)::
    Uma linguagem de programação é chamada de "Turing completo" se puder executar qualquer programa que uma máquina de Turing possa executar, com tempo e memória suficientes.

unspent transaction output (UTXO) (saída de transação não gasta)::
    UTXO é uma saída de transação não gasta que pode ser gasta como entrada em uma nova transação.

wallet (carteira)::
    Software que contém todos os seus endereços bitcoin e chaves secretas. Use-o para enviar, receber e armazenar seu bitcoin.

Wallet Import Format (WIF) (Formato de Importação de Carteira)::
    WIF ou Wallet Import Format é um formato de intercâmbio de dados projetado para permitir a exportação e importação de uma única chave privada com um sinalizador indicando se ela usa ou não uma chave pública compactada.

Algumas definições contribuídas foram obtidas sob uma licença CC-BY da https://en.bitcoin.it/wiki/Main_Page[bitcoin Wiki] ou de outras fontes de documentação de código aberto.
