[preface]
== Prefácio

=== Escrevendo o Livro Bitcoin

((("bitcoin", "benefits of", id="BCbasicbenefits0")))((("decentralized systems", "bitcoin as")))Eu tropecei no bitcoin pela primeira vez em meados de 2011. Minha reação imediata foi mais ou menos "Pfft! Dinheiro de nerd!" e o ignorei por mais seis meses, sem perceber sua importância. Esta é uma reação que vi repetidas vezes entre muitas das pessoas mais inteligentes que conheço, o que me dá algum consolo. Na segunda vez em que me deparei com bitcoin, em uma discussão na lista de e-mails, decidi ler o white paper escrito por Satoshi Nakamoto para estudar a fonte confiável e ver do que se tratava. ((("digital currencies", "bitcoin vs. others")))Ainda me lembro do momento em que terminei de ler aquelas nove páginas, quando percebi que o bitcoin não era simplesmente uma moeda digital, mas uma rede de confiança que também poderia fornecer a base para muito mais do que apenas moedas. A constatação de que "isso não é dinheiro, é uma rede de confiança descentralizada", me iniciou em uma jornada de quatro meses para devorar cada fragmento de informação sobre bitcoin que pude encontrar. Fiquei obcecado e fascinado, gastando 12 ou mais horas por dia grudado em uma tela, lendo, escrevendo, codificando e aprendendo tanto quanto podia. Saí desse estado de fuga, mais de 10 quilos mais leve pela falta de refeições consistentes, decidido a me dedicar ao trabalho com bitcoin.

Dois anos depois, após criar várias pequenas startups para explorar vários serviços e produtos relacionados ao bitcoin, decidi que era hora de escrever meu primeiro livro. Bitcoin foi o tópico que me levou a um frenesi de criatividade e consumiu meus pensamentos; foi a tecnologia mais interessante que encontrei desde a internet. Agora era a hora de compartilhar minha paixão por essa tecnologia incrível com um público mais amplo.

=== Audiência pretendida

((("intended audience")))Este livro destina-se principalmente a programadores. Se você puder usar uma linguagem de programação, este livro irá ensiná-lo como as moedas criptográficas funcionam, como usá-las e como desenvolver um software que funcione com elas. Os primeiros capítulos também são adequados como uma introdução aprofundada ao bitcoin para não codificadores - aqueles que tentam entender o funcionamento interno do bitcoin e das criptomoedas.

=== Por que Existem Insetos na Capa?

((("decentralized systems", "in nature")))A formiga cortadeira é uma espécie que exibe um comportamento altamente complexo em um superorganismo de colônia, mas cada formiga individual opera segundo um conjunto de regras simples impulsionadas pela interação social e pela troca de cheiros químicos (feromônios). De acordo com a Wikipedia: "Ao lado dos humanos, as formigas cortadeiras formam as maiores e mais complexas sociedades animais da Terra." As formigas cortadeiras na verdade não comem folhas, mas as usam para cultivar um fungo, que é a fonte central de alimento para a colônia. Pegue isso? Essas formigas estão cultivando!

Embora as formigas formem uma sociedade baseada em castas e tenham uma rainha para a produção de descendentes, não há autoridade central ou líder em uma colônia de formigas. O comportamento altamente inteligente e sofisticado exibido por uma colônia de milhões de membros é uma propriedade emergente da interação dos indivíduos em uma rede social.

A natureza demonstra que sistemas descentralizados podem ser resilientes e podem produzir complexidade emergente e sofisticação incrível sem a necessidade de uma autoridade central, hierarquia ou partes complexas.

((("decentralized systems", "benefits of")))Bitcoin é uma rede de confiança descentralizada altamente sofisticada que pode suportar uma miríade de processos financeiros. Ainda assim, cada nó na rede bitcoin segue algumas regras matemáticas simples. A interação entre muitos nós é o que leva ao surgimento do comportamento sofisticado, não qualquer complexidade inerente ou confiança em um único nó. Como uma colônia de formigas, a rede bitcoin é uma rede resiliente de nós simples seguindo regras simples que, juntas, podem fazer coisas incríveis sem qualquer coordenação central.((("", startref="BCbasicbenefits0")))

=== Convenções Utilizadas Neste Livro

((("typographical conventions")))As seguintes convenções tipográficas são usadas neste livro:

_Italic_:: Indica novos termos, URLs, endereços de e-mail, nomes de arquivos e extensões de arquivos.

+Largura constante+:: Usado para listagens de programa, bem como dentro de parágrafos para se referir a elementos de programa como nomes de variáveis ou funções, bancos de dados, tipos de dados, variáveis de ambiente, instruções e palavras-chave.

**`Largura constante em negrito`**:: Mostra comandos ou outro texto que deve ser digitado literalmente pelo usuário.

_++Largura constante em itálico++_:: Mostra o texto que deve ser substituído por valores fornecidos pelo usuário ou por valores determinados pelo contexto.


[TIP]
====
Este ícone significa uma dica ou sugestão.
====

[NOTE]
====
Este ícone significa uma nota geral.
====

[WARNING]
====
Este ícone indica um aviso ou cuidado.
====

=== Exemplos de Código

((("code examples, obtaining and using", id="codeuse00")))Os exemplos são ilustrados em Python, C++ e usando a linha de comando de um sistema operacional semelhante ao Unix, como Linux ou macOS. Todos os snippets de código estão disponíveis no repositório GitHub (https://github.com/bitcoinbook/bitcoinbook[https://github.com/bitcoinbook/bitcoinbook]) no subdiretório _code_ do repo principal. Faça um fork do código do livro, tente os exemplos de código ou envie correções via GitHub.

Todos os fragmentos de código podem ser replicados na maioria dos sistemas operacionais com uma instalação mínima de compiladores e interpretadores para as linguagens correspondentes. Quando necessário, fornecemos instruções básicas de instalação e exemplos passo a passo do resultado dessas instruções.

Alguns trechos de código e saída de código foram reformatados para impressão. Em todos esses casos, as linhas foram divididas por um caractere de barra invertida (\), seguido por um caractere de nova linha. Ao transcrever os exemplos, remova esses dois caracteres e junte as linhas novamente e você verá resultados idênticos, conforme mostrado no exemplo.

Todos os fragmentos de código usam valores reais e cálculos sempre que possível, para que você possa construir de exemplo a exemplo e ver os mesmos resultados em qualquer código que você escrever para calcular os mesmos valores. Por exemplo, as chaves privadas e as chaves públicas e endereços correspondentes são todas reais. As transações de amostra, blocos e referências de blockchain foram todos introduzidos no blockchain bitcoin real e fazem parte do livro razão público, portanto, você pode revisá-los em qualquer sistema bitcoin.

=== Usando Exemplos de Código

Este livro está aqui para ajudá-lo a realizar seu trabalho. Em geral, se o código de exemplo é oferecido com este livro, você pode usá-lo em seus programas e documentação. Você não precisa entrar em contato conosco para obter permissão, a menos que esteja reproduzindo uma parte significativa do código. Por exemplo, escrever um programa que usa vários pedaços de código deste livro não requer permissão. Vender ou distribuir um CD-ROM de exemplos de livros O’Reilly requer permissão. Responder a uma pergunta citando este livro e citando um código de exemplo não requer permissão. Incorporar uma quantidade significativa de código de exemplo deste livro na documentação do seu produto requer permissão.

((("attribution")))Agradecemos, mas não exigimos atribuição. Uma atribuição geralmente inclui o título, autor, editora e ISBN. Por exemplo: “_Dominando Bitcoin_ por Andreas M. Antonopoulos (O’Reilly). Copyright 2017 Andreas M. Antonopoulos, 978-1-491-95438-6.”

((("open source licenses")))Algumas edições deste livro são oferecidas sob uma licença de código aberto, como https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC], nesse caso, os termos dessa licença se aplicam.

Se você sentir que o uso de exemplos de código está fora do uso justo ou da permissão fornecida acima, sinta-se à vontade para nos contatar em pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Endereços e Transações de Bitcoin Neste Livro

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))Os endereços bitcoin, transações, chaves, códigos QR e dados de blockchain usados neste livro são, em sua maior parte, reais. Isso significa que você pode navegar no blockchain, olhar as transações oferecidas como exemplos, recuperá-las com seus próprios scripts ou programas, etc.

No entanto, observe que as chaves privadas usadas para construir endereços estão impressas neste livro ou foram "queimadas". Isso significa que se você enviar dinheiro para qualquer um desses endereços, o dinheiro será perdido para sempre ou, em alguns casos, qualquer pessoa que possa ler o livro pode pegá-lo usando as chaves privadas impressas aqui.

[WARNING]
====
NÃO ENVIE DINHEIRO PARA NENHUM DOS ENDEREÇOS NESTE LIVRO. Seu dinheiro será levado por outro leitor ou perdido para sempre.((("", startref="codeuse00")))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (anteriormente Safari Books Online) é um treinamento baseado em associação e plataforma de referência para empresas, governos, educadores e indivíduos.
====

Os membros têm acesso a milhares de livros, vídeos de treinamento, caminhos de aprendizagem, tutoriais interativos e listas de reprodução selecionadas de mais de 250 editoras, incluindo O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, e Course Technology, entre outros.

Para mais informações por favor visite pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

=== Como Entrar Em Contato Conosco

((("comments and questions")))((("contact information")))Envie comentários e perguntas sobre este livro ao editor:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (nos Estados Unidos ou Canadá)</li>
  <li>707-829-0515 (internacional ou local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Para comentar ou fazer perguntas técnicas sobre este livro, envie e-mail para pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

Para obter mais informações sobre nossos livros, cursos, conferências e notícias, consulte nosso site em link:$$http://www.oreilly.com$$[].

Encontre-nos no Facebook: link:$$http://facebook.com/oreilly$$[]

Siga-nos no Twitter: link:$$http://twitter.com/oreillymedia$$[]

Veja-nos no YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

[role="pagebreak-before"]
=== Entrando Em Contato Com O Autor

Você pode entrar em contato comigo, Andreas M. Antonopoulos, no meu site pessoal:
link:$$https://antonopoulos.com/$$[]

Informações sobre _Dominando Bitcoin_, bem como a Open Edition e traduções estão disponíveis em:
link:$$https://bitcoinbook.info/$$[]

Siga-me no facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Siga-me no twitter:
link:$$https://twitter.com/aantonop$$[]

Siga-me no Linkedin:
link:$$https://linkedin.com/company/aantonop$$[]

Muito obrigado a todos os meus patrocinadores que apoiam meu trabalho por meio de doações mensais. Você pode seguir minha página do Patreon aqui:
link:$$https://patreon.com/aantonop$$[]

=== Agradecimentos

((("acknowledgments", id="acknowledge0")))Este livro representa os esforços e contribuições de muitas pessoas. Sou grato por toda a ajuda que recebi de amigos, colegas e até mesmo estranhos, que se juntaram a mim neste esforço para escrever o livro técnico definitivo sobre criptomoedas e bitcoin.

É impossível fazer uma distinção entre a tecnologia bitcoin e a comunidade bitcoin, e este livro é tanto um produto dessa comunidade quanto um livro sobre a tecnologia. Meu trabalho neste livro foi encorajado, apoiado, apoiado e recompensado por toda a comunidade bitcoin desde o início até o fim. Mais do que tudo, este livro me permitiu fazer parte de uma comunidade maravilhosa por dois anos e não posso agradecer o suficiente por me aceitar nessa comunidade. Há muitas pessoas para mencionar pelo nome - pessoas que conheci em conferências, eventos, seminários, encontros, pizzarias e pequenas reuniões privadas, assim como muitas que se comunicaram comigo pelo Twitter, no reddit, no bitcointalk.org e no GitHub, que tiveram um impacto sobre este livro. Cada ideia, analogia, pergunta, resposta e explicação que você encontra neste livro foi em algum ponto inspirada, testada ou aprimorada por meio de minhas interações com a comunidade. Obrigado a todos pelo apoio; sem você este livro não teria acontecido. Sou eternamente grato.

A jornada para se tornar um autor começa muito antes do primeiro livro, é claro. Minha primeira língua (e escolaridade) foi o grego, então tive que fazer um curso de redação em inglês no meu primeiro ano de universidade. Devo agradecimentos a Diana Kordas, minha professora de redação em inglês, que me ajudou a desenvolver minha confiança e minhas habilidades naquele ano. Mais tarde, como profissional, desenvolvi minhas habilidades de redação técnica no tópico de data centers, escrevendo para a revista _Network World_. Devo agradecimentos a John Dix e John Gallant, que me deram meu primeiro emprego como redator como colunista na _Network World_, e ao meu editor Michael Cooney e meu colega Johna Till Johnson, que editou minhas colunas e as tornou adequadas para publicação. Escrever 500 palavras por semana durante quatro anos me deu experiência suficiente para pensar em me tornar um autor.

Agradeço também àqueles que me apoiaram quando apresentei minha proposta de livro à O'Reilly, fornecendo referências e revisando a proposta. Especificamente, obrigado a John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver e Jon Matonis. Agradecimentos especiais a Richard Kagan e Tymon Mattoszko, que revisaram as versões anteriores da proposta, e a Matthew Taylor, que copiou a proposta.

Agradeço a Cricket Liu, autor do título da O'Reilly _DNS e BIND_, que me apresentou a O'Reilly. Agradeço também a Michael Loukides e Allyson MacDonald da O'Reilly, que trabalharam durante meses para ajudar a fazer este livro acontecer. Allyson era especialmente paciente quando os prazos eram perdidos e as entregas atrasadas, pois a vida interferia em nosso cronograma planejado. Para a segunda edição, agradeço a Timothy McGovern por guiar o processo, Kim Cofer pela pacientemente edição e Rebecca Panzer por ilustrar muitos novos diagramas.

Os primeiros rascunhos dos primeiros capítulos foram os mais difíceis, porque o bitcoin é um assunto difícil de desvendar. Cada vez que puxei um fio da tecnologia bitcoin, tive que puxar a coisa toda. Eu repetidamente fiquei paralisado e um pouco desanimado enquanto lutava para tornar o tópico fácil de entender e criar uma narrativa em torno de um assunto técnico tão denso. Eventualmente, decidi contar a história do bitcoin através das histórias das pessoas que usam bitcoin e todo o livro se tornou muito mais fácil de escrever. Devo agradecimentos ao meu amigo e mentor, Richard Kagan, que me ajudou a desvendar a história e superar os momentos de bloqueio de escritor. Agradeço a Pamela Morgan, que revisou os primeiros rascunhos de cada capítulo na primeira e na segunda edição do livro e fez as perguntas difíceis para torná-los melhores. Além disso, obrigado aos desenvolvedores do grupo Meetup de Desenvolvedores de Bitcoin de São Francisco, bem como a Taariq Lewis e Denise Terry por ajudarem a testar o material inicial. Obrigado também a Andrew Naugler pelo design infográfico.

Durante o desenvolvimento do livro, disponibilizei os primeiros rascunhos no GitHub e solicitei comentários públicos. Mais de cem comentários, sugestões, correções e contribuições foram enviados em resposta. Essas contribuições são explicitamente reconhecidas, com meus agradecimentos, em <<github_contrib>>. Acima de tudo, meus sinceros agradecimentos aos meus editores voluntários do GitHub, Ming T. Nguyen (1ª edição) e Will Binns (2ª edição), que trabalharam incansavelmente para selecionar, gerenciar e resolver solicitações pull, relatórios de problemas e realizar correções de bugs no GitHub.

Depois que o livro foi redigido, ele passou por várias rodadas de revisão técnica. Agradecemos a Cricket Liu e Lorne Lantz por sua análise completa, comentários e apoio.

Vários desenvolvedores de bitcoins contribuíram com amostras de código, análises, comentários e encorajamento. Agradecimentos a Amir Taaki e Eric Voskuil por exemplos de trechos de código e muitos comentários excelentes; Chris Kleeschulte por contribuir com o apêndice Bitcore; Vitalik Buterin e Richard Kiss pela ajuda com matemática da curva elíptica e contribuições de código; Gavin Andresen pelas correções, comentários e incentivo; Michalis Kargakis pelos comentários, contribuições e redação do btcd; e Robin Inge pelos envios de erratas, melhorando a segunda impressão. Na segunda edição, recebi novamente muita ajuda de muitos desenvolvedores Bitcoin Core, incluindo Eric Lombrozo que desmistificou Testemunha Segregada, Luke Dashjr que ajudou a melhorar o capítulo sobre transações, Johnson Lau que revisou o Testemunha Segregada e outros capítulos, e muitos outros. Devo agradecimentos a Joseph Poon, Tadge Dryja e Olaoluwa Osuntokun, que explicaram a Rede Relâmpago, revisaram minha redação e responderam às perguntas quando fiquei sem saber o que fazer.

Devo meu amor pelas palavras e pelos livros à minha mãe, Theresa, que me criou em uma casa com livros em todas as paredes. Minha mãe também comprou meu primeiro computador em 1982, apesar de se descrever como um tecnófobo. Meu pai, Menelaos, engenheiro civil que acaba de publicar seu primeiro livro aos 80 anos, foi quem me ensinou o pensamento lógico e analítico e o amor pela ciência e engenharia.

Obrigado a todos por me apoiarem nesta jornada.


////
Agradecimentos do contribuidor do Github em um novo arquivo...
////

include::github_contrib.asciidoc[]
